FROM node:14

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm install

# Copy tsconfig and code
COPY tsconfig*.json ./
COPY src .
COPY nest-cli.json .

# Build the NestJS application
RUN npm run build

EXPOSE 3000
CMD [ "node", "dist/main" ]